service: notifications
app: fiap-hackathon-g41

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  environment:
    NOTIFICATIONS_SQS_ARN: ${param:NOTIFICATIONS_SQS_ARN}
    SMTP_HOST: ${param:SMTP_HOST}
    SMTP_PORT: ${param:SMTP_PORT}
    SMTP_USERNAME: ${param:SMTP_USERNAME}
    SMTP_PASSWORD: ${param:SMTP_PASSWORD}
    SENDER_EMAIL: ${param:SENDER_EMAIL}
  role: ${param:LAB_ROLE_ARN}

custom:
  serverless-offline:
    useChildProcesses: true
    noPrependStageInUrl: true
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'prisma'
      - '@prisma/client'
      - 'aws-sdk'
      - '@aws-sdk/*'
    target: node20
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
    watch:
      pattern:
        - src/**/*.ts

functions:
  notifications:
    handler: src/handler.handler
    events:
      - sqs:
          arn: ${self:provider.environment.NOTIFICATIONS_SQS_ARN}
plugins:
  - serverless-offline
  - serverless-esbuild

package:
  individually: true
  patterns:
    - '!node_modules/**'
