name: Deploy PRD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20
  STAGE: prd
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  deploy:
    name: Deploy to PRD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Serverless deploy
        run: |
          yarn serverless deploy \
            --stage ${{ env.STAGE }} \
            --region ${{ env.AWS_REGION }} \
            --verbose \
            --param="NOTIFICATIONS_SQS_ARN=${{ secrets.NOTIFICATIONS_SQS_ARN }}" \
            --param="LAB_ROLE_ARN=${{ secrets.LAB_ROLE_ARN }}" \
            --param="SMTP_HOST=${{ secrets.SMTP_HOST }}" \
            --param="SMTP_PORT=${{ secrets.SMTP_PORT }}" \
            --param="SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" \
            --param="SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" \
            --param="SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
